import Head from "next/head";
import Header from "./components/Header";
import LargeCard from "./components/LargeCard";
import ProductView from "./components/ProductView";

export default function Home({ productData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='max-w-7xl bg-gray-100 min-h-screen mx-auto px-8 sm:px-16'>
        <section className='mt-2'>
          <LargeCard products={productData} />
        </section>

        <section className='flex justify-evenly space-x-3'>
          <ProductView />
          <ProductView />
          <ProductView />
        </section>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const productData = await fetch(
    "https://api.npoint.io/17be4564ae3977957f1f"
  ).then((res) => res.json());

  return {
    props: {
      productData,
    },
  };
}
